### ISSUE TITLE
Help for first time user

### ISSUE THREAD

**Issue by GilGrafik** [genmon/sirius#24]
Hello,

I have just bought a little printer.

Can you tell if the printer will work over a wifi connection or does it always need to be plugged in directly into a ethernet ?

thanks in advance for your help everyone

**Comment by Meroje** [comment]
The bridge doesn't have wifi connectivity, only ethernet. The communication between the bridge and the printer is wireless.

**Comment by GilGrafik** [comment]
Ok thanks for confirming and helping me
